[Namespaces]
Namespace1=full
Namespace2=class_based
Namespace3=workbench
Namespace4=bug_fixes

; ===================================================================

[full]
IniName=full.ini
InfoName=full.rtf
DataPath=class
Name=Class-Based Properties + Workbench Attunement
Description=This option gives the Quest Crystal differing properties based on your character class and allows you to attune the crystal yourself at a workbench.

[class_based]
IniName=class_based.ini
InfoName=class_based.rtf
DataPath=class
Name=Class-Based Properties
Description=This option gives the Quest Crystal differing properties based on your character class.

[workbench]
IniName=workbench.ini
InfoName=workbench.rtf
DataPath=standard
Name=Workbench Attunement
Description=This option allows you to attune the Quest Crystal yourself at a workbench.

[bug_fixes]
IniName=bug_fixes.ini
InfoName=bug_fixes.rtf
DataPath=standard
Name=Bug Fixes Only
Description=This option installs only the bug fixes for spawning the Quest Crystal that are included with the other options.