[Settings]
FileExists=1
WindowCaption=JC's Crystal Attunement for K2
ConfirmMessage=N/A
LogLevel=3
InstallerMode=1
BackupFiles=1
PlaintextLog=0
LookupGameFolder=0
LookupGameNumber=2
SaveProcessedScripts=0


[TLKList]


[InstallList]
install_folder0=Override
install_folder1=Modules
install_folder2=Modules\604dan.mod


[2DAList]


[GFFList]


[CompileList]


[SSFList]


; ===================================================================


[install_folder0]
Replace0=a_q_cryst_change.ncs
Replace1=c_q_cryst_change.ncs
Replace2=jc_c_wb_qc.ncs
Replace2=jc_compdlg.ncs
Replace4=jc_wb_qc.dlg
Replace5=workbnch.dlg


[install_folder1]
File0=604dan.mod


[install_folder2]
Replace0=a_q_cryst_first.ncs